// npm_player/packages/svelte/src/controls/SkipButton.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { readable } from "svelte/store";
  import type { Readable } from "svelte/store";
  import { createTranslator, type TranslateFn } from "@livepeer-frameworks/player-core";
  import { SkipBackIcon, SkipForwardIcon } from "../icons";

  interface Props {
    direction: "back" | "forward";
    seconds?: number;
  }

  let { direction, seconds = 10 }: Props = $props();
  let pc: any = getContext("fw-player-controller");
  const translatorStore: Readable<TranslateFn> =
    getContext<Readable<TranslateFn> | undefined>("fw-translator") ??
    readable(createTranslator({ locale: "en" }));
  let t: TranslateFn = $derived($translatorStore);

  let label = $derived(direction === "back" ? t("skipBackward") : t("skipForward"));
</script>

<button
  type="button"
  class="fw-btn-flush"
  aria-label={label}
  title={label}
  onclick={() =>
    pc?.seek((pc?.currentTime ?? 0) + (direction === "back" ? -seconds * 1000 : seconds * 1000))}
>
  {#if direction === "back"}
    <SkipBackIcon size={16} />
  {:else}
    <SkipForwardIcon size={16} />
  {/if}
</button>

// npm_player/packages/react/src/components/controls/SkipButton.tsx
import React from "react";
import { usePlayerContextOptional } from "../../context/player";
import { useTranslate } from "../../context/i18n";
import { SkipBackIcon, SkipForwardIcon } from "../Icons";

export interface SkipButtonProps {
  direction: "back" | "forward";
  seconds?: number;
  onSkip?: () => void;
  size?: number;
  className?: string;
}

export const SkipButton: React.FC<SkipButtonProps> = ({
  direction,
  seconds = 10,
  onSkip,
  size = 16,
  className,
}) => {
  const ctx = usePlayerContextOptional();
  const t = useTranslate();
  const Icon = direction === "back" ? SkipBackIcon : SkipForwardIcon;
  const delta = direction === "back" ? -seconds : seconds;
  const label = direction === "back" ? t("skipBackward") : t("skipForward");
  const title = direction === "back" ? `${t("seekBackward")} (j)` : `${t("seekForward")} (l)`;

  const handleClick = onSkip ?? (() => ctx?.seekBy(delta));

  return (
    <button
      type="button"
      className={className ?? "fw-btn-flush"}
      aria-label={label}
      title={title}
      onClick={handleClick}
    >
      <Icon size={size} />
    </button>
  );
};
