// npm_studio/packages/svelte/src/components/StudioPreview.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { Readable } from "svelte/store";
  import {
    createStudioTranslator,
    type StudioTranslateFn,
  } from "@livepeer-frameworks/streamcrafter-core";
  import CameraIcon from "../icons/CameraIcon.svelte";

  let pc: any = getContext("fw-sc-controller");
  const translatorCtx = getContext<Readable<StudioTranslateFn> | undefined>("fw-sc-translator");
  const fallbackT = createStudioTranslator({ locale: "en" });
  let t: StudioTranslateFn = $derived(translatorCtx ? $translatorCtx : fallbackT);

  let videoEl: HTMLVideoElement;

  $effect(() => {
    if (videoEl && pc?.mediaStream) {
      videoEl.srcObject = pc.mediaStream;
      videoEl.play().catch(() => {});
    } else if (videoEl) {
      videoEl.srcObject = null;
    }
  });

  let statusText = $derived.by(() => {
    if (pc?.state === "connecting") return t("connecting");
    if (pc?.state === "reconnecting") return t("reconnecting");
    return "";
  });
</script>

<div class="fw-sc-preview-wrapper">
  <div class="fw-sc-preview">
    <video bind:this={videoEl} playsinline muted autoplay aria-label={t("streamPreview")}></video>

    {#if !pc?.mediaStream}
      <div class="fw-sc-preview-placeholder">
        <CameraIcon size={48} />
        <span>{t("addSourcePrompt")}</span>
      </div>
    {/if}

    {#if pc?.state === "connecting" || pc?.state === "reconnecting"}
      <div class="fw-sc-status-overlay">
        <div class="fw-sc-status-spinner"></div>
        <span class="fw-sc-status-text">{statusText}</span>
      </div>
    {/if}

    {#if pc?.isStreaming}
      <div class="fw-sc-live-badge">{t("live")}</div>
    {/if}
  </div>
</div>

// npm_studio/packages/react/src/components/StudioPreview.tsx
import React, { useEffect, useRef } from "react";
import { useStreamCrafterContext } from "../context/StreamCrafterContext";
import { useStudioTranslate } from "../context/StudioI18nContext";
import { useCompositor } from "../hooks/useCompositor";
import { CompositorControls } from "./CompositorControls";
import type { MediaSource } from "@livepeer-frameworks/streamcrafter-core";

const CameraIcon = ({ size = 18 }: { size?: number }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M23 7l-7 5 7 5V7z" />
    <rect x="1" y="5" width="15" height="14" rx="2" ry="2" />
  </svg>
);

export interface StudioPreviewProps {
  /** Enable compositor overlay controls */
  enableCompositor?: boolean;
  /** Compositor config */
  compositorConfig?: {
    renderer?: "auto" | "webgpu" | "webgl" | "canvas2d";
    width?: number;
    height?: number;
    frameRate?: number;
  };
  /** Override sources (falls back to context) */
  sources?: MediaSource[];
}

export const StudioPreview: React.FC<StudioPreviewProps> = ({
  enableCompositor = true,
  compositorConfig,
  sources: propSources,
}) => {
  const ctx = useStreamCrafterContext();
  const t = useStudioTranslate();
  const videoRef = useRef<HTMLVideoElement>(null);
  const sources = propSources ?? ctx.sources;

  const compositor = useCompositor({
    controller: enableCompositor ? ctx.getController() : null,
    autoEnable: enableCompositor,
    config: compositorConfig,
  });

  useEffect(() => {
    if (videoRef.current && ctx.mediaStream) {
      videoRef.current.srcObject = ctx.mediaStream;
      videoRef.current.play().catch(() => {});
    } else if (videoRef.current) {
      videoRef.current.srcObject = null;
    }
  }, [ctx.mediaStream]);

  const statusText =
    ctx.state === "connecting"
      ? t("connecting")
      : ctx.state === "reconnecting"
        ? t("reconnecting")
        : "";

  return (
    <div className="fw-sc-preview-wrapper">
      <div className="fw-sc-preview">
        <video ref={videoRef} playsInline muted autoPlay aria-label={t("streamPreview")} />

        {!ctx.mediaStream && (
          <div className="fw-sc-preview-placeholder">
            <CameraIcon size={48} />
            <span>{t("addSourcePrompt")}</span>
          </div>
        )}

        {(ctx.state === "connecting" || ctx.state === "reconnecting") && (
          <div className="fw-sc-status-overlay">
            <div className="fw-sc-status-spinner" />
            <span className="fw-sc-status-text">{statusText}</span>
          </div>
        )}

        {ctx.isStreaming && <div className="fw-sc-live-badge">{t("live")}</div>}

        {enableCompositor && (
          <CompositorControls
            isEnabled={compositor.isEnabled}
            isInitialized={compositor.isInitialized}
            rendererType={compositor.rendererType}
            stats={compositor.stats}
            sources={sources}
            layers={compositor.activeScene?.layers ?? []}
            currentLayout={compositor.currentLayout}
            onLayoutApply={compositor.applyLayout}
            onCycleSourceOrder={(direction) => compositor.cycleSourceOrder(direction)}
          />
        )}
      </div>
    </div>
  );
};
