// npm_player/packages/react/src/components/controls/FullscreenButton.tsx
import React from "react";
import { usePlayerContextOptional } from "../../context/player";
import { useTranslate } from "../../context/i18n";
import { FullscreenToggleIcon } from "../Icons";

export interface FullscreenButtonProps {
  isFullscreen?: boolean;
  onToggle?: () => void;
  size?: number;
  className?: string;
}

export const FullscreenButton: React.FC<FullscreenButtonProps> = ({
  isFullscreen: propIsFullscreen,
  onToggle,
  size = 16,
  className,
}) => {
  const ctx = usePlayerContextOptional();
  const t = useTranslate();
  const isFullscreen = propIsFullscreen ?? ctx?.state.isFullscreen ?? false;
  const handleClick = onToggle ?? (() => ctx?.toggleFullscreen());

  return (
    <button
      type="button"
      className={className ?? "fw-btn-flush"}
      aria-label={isFullscreen ? t("exitFullscreen") : t("fullscreen")}
      aria-pressed={isFullscreen}
      title={isFullscreen ? `${t("exitFullscreen")} (f)` : `${t("fullscreen")} (f)`}
      onClick={handleClick}
    >
      <FullscreenToggleIcon isFullscreen={isFullscreen} size={size} />
    </button>
  );
};

// npm_player/packages/svelte/src/controls/FullscreenButton.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { readable } from "svelte/store";
  import type { Readable } from "svelte/store";
  import { createTranslator, type TranslateFn } from "@livepeer-frameworks/player-core";
  import { FullscreenIcon, FullscreenExitIcon } from "../icons";

  let pc: any = getContext("fw-player-controller");
  const translatorStore: Readable<TranslateFn> =
    getContext<Readable<TranslateFn> | undefined>("fw-translator") ??
    readable(createTranslator({ locale: "en" }));
  let t: TranslateFn = $derived($translatorStore);
</script>

<button
  type="button"
  class="fw-btn-flush"
  aria-label={pc?.isFullscreen ? t("exitFullscreen") : t("fullscreen")}
  aria-pressed={pc?.isFullscreen ?? false}
  title={pc?.isFullscreen ? t("exitFullscreen") : t("fullscreen")}
  onclick={() => pc?.toggleFullscreen()}
>
  {#if pc?.isFullscreen}
    <FullscreenExitIcon size={16} />
  {:else}
    <FullscreenIcon size={16} />
  {/if}
</button>
