// npm_player/packages/react/src/components/controls/LiveBadge.tsx
import React from "react";
import { usePlayerContextOptional } from "../../context/player";
import { useTranslate } from "../../context/i18n";
import { cn } from "@livepeer-frameworks/player-core";
import { SeekToLiveIcon } from "../Icons";

export interface LiveBadgeProps {
  isLive?: boolean;
  isNearLive?: boolean;
  onJumpToLive?: () => void;
  className?: string;
}

export const LiveBadge: React.FC<LiveBadgeProps> = ({
  isLive: propIsLive,
  isNearLive: propIsNearLive,
  onJumpToLive,
  className,
}) => {
  const ctx = usePlayerContextOptional();
  const t = useTranslate();

  const isLive = propIsLive ?? ctx?.state.isEffectivelyLive ?? false;
  const isNearLive = propIsNearLive ?? true;
  const handleClick = onJumpToLive ?? (() => ctx?.jumpToLive());

  if (!isLive) return null;

  return (
    <button
      type="button"
      className={cn(
        "fw-live-badge",
        isNearLive ? "fw-live-badge--active" : "fw-live-badge--behind",
        className
      )}
      onClick={handleClick}
      disabled={isNearLive}
      title={t("live")}
    >
      {t("live").toUpperCase()}
      {!isNearLive && <SeekToLiveIcon size={10} />}
    </button>
  );
};

// npm_player/packages/svelte/src/controls/LiveBadge.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { readable } from "svelte/store";
  import type { Readable } from "svelte/store";
  import { createTranslator, type TranslateFn } from "@livepeer-frameworks/player-core";
  import { SeekToLiveIcon } from "../icons";

  let pc: any = getContext("fw-player-controller");
  const translatorStore: Readable<TranslateFn> =
    getContext<Readable<TranslateFn> | undefined>("fw-translator") ??
    readable(createTranslator({ locale: "en" }));
  let t: TranslateFn = $derived($translatorStore);
</script>

{#if pc?.isEffectivelyLive}
  <button
    type="button"
    class="fw-live-badge fw-live-badge--active"
    onclick={() => pc?.jumpToLive()}
    aria-label={t("live")}
  >
    {t("live").toUpperCase()}
    <SeekToLiveIcon size={10} />
  </button>
{/if}
