// npm_player/packages/react/src/components/controls/PlayButton.tsx
import React from "react";
import { usePlayerContextOptional } from "../../context/player";
import { useTranslate } from "../../context/i18n";
import { PlayPauseIcon } from "../Icons";

export interface PlayButtonProps {
  isPlaying?: boolean;
  onToggle?: () => void;
  size?: number;
  className?: string;
}

export const PlayButton: React.FC<PlayButtonProps> = ({
  isPlaying: propIsPlaying,
  onToggle,
  size = 18,
  className,
}) => {
  const ctx = usePlayerContextOptional();
  const t = useTranslate();
  const isPlaying = propIsPlaying ?? ctx?.state.isPlaying ?? false;
  const handleClick = onToggle ?? (() => ctx?.togglePlay());

  return (
    <button
      type="button"
      className={className ?? "fw-btn-flush"}
      aria-label={isPlaying ? t("pause") : t("play")}
      aria-pressed={isPlaying}
      title={isPlaying ? `${t("pause")} (k)` : `${t("play")} (k)`}
      onClick={handleClick}
    >
      <PlayPauseIcon isPlaying={isPlaying} size={size} />
    </button>
  );
};

// npm_player/packages/svelte/src/controls/PlayButton.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { readable } from "svelte/store";
  import type { Readable } from "svelte/store";
  import { createTranslator, type TranslateFn } from "@livepeer-frameworks/player-core";
  import { PlayIcon, PauseIcon } from "../icons";

  let pc: any = getContext("fw-player-controller");
  const translatorStore: Readable<TranslateFn> =
    getContext<Readable<TranslateFn> | undefined>("fw-translator") ??
    readable(createTranslator({ locale: "en" }));
  let t: TranslateFn = $derived($translatorStore);
</script>

<button
  type="button"
  class="fw-btn-flush"
  aria-label={pc?.isPlaying ? t("pause") : t("play")}
  aria-pressed={pc?.isPlaying ?? false}
  title={pc?.isPlaying ? t("pause") : t("play")}
  onclick={() => pc?.togglePlay()}
>
  {#if pc?.isPlaying}
    <PauseIcon size={18} />
  {:else}
    <PlayIcon size={18} />
  {/if}
</button>
