// website_marketing/src/components/shared/BetaBadge.jsx
import { cn } from '@/lib/utils'

// Note: kept component name for minimal touch points; default label now reflects alpha stage.
const BetaBadge = ({ label = 'Alpha', className = '' }) => (
  <span
    className={cn(
      'beta-badge inline-flex items-center rounded-full px-2.5 py-1 text-[0.68rem] font-semibold uppercase tracking-[0.2em]',
      className
    )}
  >
    {label}
  </span>
)

export default BetaBadge

// website_application/src/lib/components/BetaBadge.svelte
<script lang="ts">
  import { Badge } from "$lib/components/ui/badge";

  interface Props {
    label?: string;
    className?: string;
    variant?: import("$lib/components/ui/badge").BadgeVariant;
    tone?: import("$lib/components/ui/badge").BadgeTone;
  }

  // Note: kept component name for minimal touch points; default label now reflects alpha stage.
  let {
    label = "Public Alpha",
    className = "",
    variant = "secondary",
    tone = undefined,
  }: Props = $props();
</script>

<Badge class={`uppercase tracking-wide ${className}`} variant={variant} tone={tone}>
  {label}
</Badge>
