// npm_player/packages/svelte/src/Player.svelte
<!--
  Player.svelte - Full-featured video player using PlayerController
  Thin wrapper over PlayerController from @livepeer-frameworks/player-core
-->
<script lang="ts">
  import { onMount, setContext, type Snippet } from "svelte";
  import IdleScreen from "./IdleScreen.svelte";
  import LoadingPoster from "./LoadingPoster.svelte";
  import SubtitleRenderer from "./SubtitleRenderer.svelte";
  import PlayerControls from "./PlayerControls.svelte";
  import SpeedIndicator from "./SpeedIndicator.svelte";
  import SkipIndicator from "./SkipIndicator.svelte";
  import TitleOverlay from "./TitleOverlay.svelte";
  import StatsPanel from "./StatsPanel.svelte";
  import DevModePanel from "./DevModePanel.svelte";
  import {
    ContextMenu,
    ContextMenuTrigger,
    ContextMenuPortal,
    ContextMenuContent,
    ContextMenuItem,
    ContextMenuSeparator,
  } from "./ui/context-menu";
  import { StatsIcon, SettingsIcon, PictureInPictureIcon } from "./icons";
  import {
    cn,
    themeOverridesToStyle,
    resolveTheme,
    type PlaybackMode,
    type ContentEndpoints,
    type PlayerState,
    type PlayerStateContext,
    type ContentType,
    type EndpointInfo,
    type PlayerMetadata,
    type FwThemePreset,
    type FwThemeOverrides,
    type FwLocale,
    type ThumbnailCue,
    type LoadingPosterInfo,
    type StreamInfo,
  } from "@livepeer-frameworks/player-core";
  import {
    createPlayerControllerStore,
    type PlayerControllerStore,
  } from "./stores/playerController";
  import { localeStore, translatorStore } from "./stores/i18n";
  import type { SkipDirection } from "./SkipIndicator.svelte";

  // Props - aligned with React Player
  interface Props {
    contentId: string;
    contentType?: ContentType;
    thumbnailUrl?: string | null;
    endpoints?: ContentEndpoints;
    options?: {
      gatewayUrl?: string;
      mistUrl?: string;
      authToken?: string;
      playbackAuth?: import("@livepeer-frameworks/player-core").PlaybackAuth;
      autoplay?: boolean;
      muted?: boolean;
      controls?: boolean;
      stockControls?: boolean;
      devMode?: boolean;
      debug?: boolean;
      forcePlayer?: string;
      forceType?: string;
      forceSource?: number;
      playbackMode?: PlaybackMode;
      theme?: FwThemePreset;
      themeOverrides?: FwThemeOverrides;
      locale?: FwLocale;
    };
    onStateChange?: (state: PlayerState, context?: PlayerStateContext) => void;
    onMetadata?: (metadata: PlayerMetadata) => void;
    children?: Snippet;
  }

  let {
    contentId,
    contentType,
    thumbnailUrl = null,
    endpoints = undefined,
    options = {},
    onStateChange = undefined,
    onMetadata = undefined,
    children = undefined,
  }: Props = $props();

  // ============================================================================
  // UI-only State (stays in wrapper)
  // ============================================================================
  let isStatsOpen = $state(false);
  let isDevPanelOpen = $state(false);
  let skipDirection: SkipDirection = $state(null);

  let activeTheme = $state<FwThemePreset>("default");
  let activeLocale = $state<FwLocale>("en");
  $effect(() => {
    if (options.theme) activeTheme = options.theme;
    if (options.locale) activeLocale = options.locale;
  });

  // Sync locale state to i18n store and provide translator context
  $effect(() => {
    localeStore.set(activeLocale);
  });
  setContext("fw-translator", translatorStore);

  // Provide context for composable controls (reactive getters)
  setContext("fw-player-controller", {
    get isPlaying() {
      return storeState.isPlaying;
    },
    get isPaused() {
      return storeState.isPaused;
    },
    get isMuted() {
      return storeState.isMuted;
    },
    get volume() {
      return storeState.volume;
    },
    get currentTime() {
      return storeState.currentTime;
    },
    get duration() {
      return storeState.duration;
    },
    get isFullscreen() {
      return storeState.isFullscreen;
    },
    get isEffectivelyLive() {
      return storeState.isEffectivelyLive;
    },
    get isBuffering() {
      return storeState.isBuffering;
    },
    get isLoopEnabled() {
      return storeState.isLoopEnabled;
    },
    get error() {
      return storeState.error;
    },
    get qualities() {
      return playerStore?.getQualities() ?? [];
    },
    togglePlay: () => playerStore?.togglePlay(),
    toggleMute: () => playerStore?.toggleMute(),
    toggleFullscreen: () => playerStore?.toggleFullscreen(),
    toggleLoop: () => playerStore?.toggleLoop(),
    setVolume: (v: number) => playerStore?.setVolume(v),
    jumpToLive: () => playerStore?.jumpToLive(),
    seek: (t: number) => playerStore?.seek(t),
    selectQuality: (id: string) => playerStore?.selectQuality(id),
    getQualities: () => playerStore?.getQualities() ?? [],
  });

  // Playback mode preference (persistent)
  let devPlaybackMode: PlaybackMode = $state("auto");
  $effect(() => {
    if (options?.playbackMode) {
      devPlaybackMode = options.playbackMode;
    }
  });

  // Error fade-out: keep overlay visible while it animates out
  let displayedError: string | null = $state(null);
  let displayedIsPassive = $state(false);
  let isErrorDismissing = $state(false);
  let errorDismissTimer: ReturnType<typeof setTimeout> | null = null;
  $effect(() => {
    const error = storeState.error;
    const passive = storeState.isPassiveError;
    if (error) {
      if (errorDismissTimer) {
        clearTimeout(errorDismissTimer);
        errorDismissTimer = null;
      }
      displayedError = error;
      displayedIsPassive = passive;
      isErrorDismissing = false;
    } else if (displayedError) {
      isErrorDismissing = true;
      errorDismissTimer = setTimeout(() => {
        displayedError = null;
        displayedIsPassive = false;
        isErrorDismissing = false;
        errorDismissTimer = null;
      }, 300);
    }
  });

  // Container ref
  let containerRef: HTMLElement | undefined = $state();
  let playerRootRef: HTMLDivElement | undefined = $state();

  // ============================================================================
  // PlayerController Store - ALL business logic
  // ============================================================================
  let playerStore: PlayerControllerStore | null = $state(null);
  let storeState = $state({
    state: "booting" as PlayerState,
    streamState: null as any,
    endpoints: null as any,
    streamInfo: null as StreamInfo | null,
    metadata: null as any,
    videoElement: null as HTMLVideoElement | null,
    currentTime: 0,
    duration: NaN,
    isPlaying: false,
    isPaused: true,
    isBuffering: false,
    isMuted: false,
    volume: 1,
    error: null as string | null,
    isPassiveError: false,
    hasPlaybackStarted: false,
    isHoldingSpeed: false,
    holdSpeed: 2,
    isHovering: false,
    shouldShowControls: false,
    isLoopEnabled: false,
    isFullscreen: false,
    isPiPActive: false,
    isEffectivelyLive: false,
    shouldShowIdleScreen: true,
    currentPlayerInfo: null as { name: string; shortname: string } | null,
    currentSourceInfo: null as { url: string; type: string } | null,
    playbackQuality: null as any,
    subtitlesEnabled: false,
    toast: null as { message: string; timestamp: number } | null,
    controllerSeekableStart: 0,
    controllerLiveEdge: 0,
    controllerCanSeek: false,
    controllerHasAudio: true,
    thumbnailCues: [] as ThumbnailCue[],
    loadingPoster: null as LoadingPosterInfo | null,
    shouldShowLoadingPoster: false,
  });

  // Track if we've already attached to prevent double-attach race
  let hasAttached = false;

  // Debug helper
  const debug = (msg: string) => {
    if (options?.debug) {
      console.log(`[Player.svelte] ${msg}`);
    }
  };

  // Create store on mount
  onMount(() => {
    debug(`onMount - contentId: ${contentId}, contentType: ${contentType}`);
    debug(`onMount - gatewayUrl: ${options?.gatewayUrl}, mistUrl: ${options?.mistUrl}`);
    debug(`onMount - endpoints: ${endpoints ? "provided" : "not provided"}`);

    playerStore = createPlayerControllerStore({
      contentId,
      contentType,
      endpoints,
      gatewayUrl: options?.gatewayUrl,
      mistUrl: options?.mistUrl,
      authToken: options?.authToken,
      playbackAuth: options?.playbackAuth,
      autoplay: options?.autoplay !== false,
      muted: options?.muted === true,
      controls: options?.stockControls === true,
      poster: thumbnailUrl || undefined,
      debug: options?.debug,
    });

    debug("playerStore created");

    // Subscribe to store state
    let prevMetadata: PlayerMetadata | null = null;
    const unsubscribe = playerStore.subscribe((state) => {
      storeState = state;
      // Forward state changes to prop callback
      if (onStateChange && state.state) {
        onStateChange(state.state);
      }
      // Forward metadata changes to prop callback
      if (onMetadata && state.metadata && state.metadata !== prevMetadata) {
        prevMetadata = state.metadata;
        onMetadata(state.metadata);
      }
    });

    return () => {
      debug("cleanup - destroying playerStore");
      unsubscribe();
      playerStore?.destroy();
      playerStore = null;
      hasAttached = false;
    };
  });

  // Attach when container becomes available (only once)
  $effect(() => {
    debug(
      `$effect - containerRef: ${!!containerRef}, playerStore: ${!!playerStore}, hasAttached: ${hasAttached}`
    );
    if (containerRef && playerStore && !hasAttached) {
      hasAttached = true;
      debug("attaching to container");
      playerStore
        .attach(containerRef)
        .then(() => {
          debug("attach completed");
        })
        .catch((err) => {
          debug(`attach failed: ${err}`);
          console.error("[Player.svelte] attach failed:", err);
        });
    }
  });

  // Auto-dismiss toast after 3 seconds
  $effect(() => {
    if (!storeState.toast) return;
    const timer = setTimeout(() => {
      playerStore?.dismissToast();
    }, 3000);
    return () => clearTimeout(timer);
  });

  // ============================================================================
  // Dev Mode Callbacks
  // ============================================================================
  function handleDevSettingsChange(settings: {
    forcePlayer?: string;
    forceType?: string;
    forceSource?: number;
  }) {
    // One-shot selection - controller handles the state
    playerStore?.setDevModeOptions({
      forcePlayer: settings.forcePlayer,
      forceType: settings.forceType,
      forceSource: settings.forceSource,
    });
  }

  function handleModeChange(mode: PlaybackMode) {
    devPlaybackMode = mode;
    // Mode is a persistent preference
    playerStore?.setDevModeOptions({ playbackMode: mode });
  }

  function handleReload() {
    playerStore?.clearError();
    playerStore?.reload();
  }

  function handleSkipIndicatorHide() {
    skipDirection = null;
  }

  // ============================================================================
  // Derived Values
  // ============================================================================
  let primaryEndpoint = $derived(storeState.endpoints?.primary as EndpointInfo | undefined);
  let isLegacyPlayer = $derived(storeState.currentPlayerInfo?.shortname === "mist-legacy");
  let useStockControls = $derived(options?.stockControls === true || isLegacyPlayer);
  let metadata = $derived(storeState.metadata);

  // Title overlay visibility: show on hover or when paused
  let showTitleOverlay = $derived(
    (storeState.isHovering || storeState.isPaused) &&
      !storeState.shouldShowIdleScreen &&
      !storeState.isBuffering &&
      !storeState.error
  );

  // Buffering spinner: only during active playback
  let showBufferingSpinner = $derived(
    !storeState.shouldShowIdleScreen &&
      storeState.isBuffering &&
      !storeState.error &&
      storeState.hasPlaybackStarted
  );

  // Waiting for endpoint (shown as overlay, not early return)
  let showWaitingForEndpoint = $derived(
    !storeState.endpoints?.primary && storeState.state !== "booting"
  );

  let waitingMessage = $derived(
    options?.gatewayUrl
      ? storeState.state === "gateway_loading"
        ? $translatorStore("resolvingEndpoint")
        : $translatorStore("waitingForStream")
      : $translatorStore("waitingForStream")
  );
  let streamStateMessage = $derived(storeState.streamState?.message);
  let streamStateError = $derived(storeState.streamState?.error);
  let idleMessage = $derived(
    storeState.isEffectivelyLive
      ? streamStateError || streamStateMessage
      : $translatorStore("loading")
  );
  let idleDetails = $derived(
    options?.devMode &&
      streamStateError &&
      streamStateMessage &&
      streamStateError !== streamStateMessage
      ? streamStateMessage
      : undefined
  );
  // Controller owns the visibility decision (PlayerController.getShouldShowLoadingPoster).
  // Wrapper masks with its local displayedError fade lifecycle.
  let showLoadingPosterOverlay = $derived(storeState.shouldShowLoadingPoster && !displayedError);
</script>

<ContextMenu>
  <ContextMenuTrigger>
    {#snippet child({ props })}
      <div
        bind:this={playerRootRef}
        {...props}
        class={cn(
          "fw-player-surface fw-player-root relative w-full h-full bg-black",
          options?.devMode && "flex"
        )}
        data-player-container="true"
        data-theme={activeTheme && activeTheme !== "default" ? activeTheme : undefined}
        style={(() => {
          const presetOverrides = activeTheme ? resolveTheme(activeTheme) : null;
          const merged = { ...presetOverrides, ...options?.themeOverrides };
          return Object.keys(merged).length > 0
            ? Object.entries(themeOverridesToStyle(merged))
                .map(([k, v]) => `${k}: ${v}`)
                .join("; ")
            : undefined;
        })()}
        role="region"
        aria-label="Video player"
        onmouseenter={() => playerStore?.handleMouseEnter()}
        onmouseleave={() => playerStore?.handleMouseLeave()}
        onmousemove={() => playerStore?.handleMouseMove()}
      >
        <!-- Player area -->
        <div class={cn("relative", options?.devMode ? "flex-1 min-w-0 h-full" : "w-full h-full")}>
          <!-- Video container - PlayerController attaches here -->
          <div bind:this={containerRef} class="fw-player-container w-full h-full"></div>

          <!-- Subtitle renderer -->
          {#if storeState.subtitlesEnabled}
            <SubtitleRenderer
              currentTime={storeState.currentTime}
              enabled={storeState.subtitlesEnabled}
            />
          {/if}

          <!-- Title overlay -->
          <TitleOverlay
            title={metadata?.title}
            description={metadata?.description}
            isVisible={showTitleOverlay}
          />

          <!-- Stats panel -->
          <StatsPanel
            isOpen={isStatsOpen}
            onClose={() => (isStatsOpen = false)}
            {metadata}
            streamState={storeState.streamState}
            quality={storeState.playbackQuality}
            videoElement={storeState.videoElement}
            protocol={primaryEndpoint?.protocol}
            nodeId={primaryEndpoint?.nodeId}
            geoDistance={primaryEndpoint?.geoDistance}
          />

          <!-- Dev mode toggle (when panel closed) -->
          {#if options?.devMode && !isDevPanelOpen}
            <DevModePanel
              onSettingsChange={handleDevSettingsChange}
              playbackMode={devPlaybackMode}
              onModeChange={handleModeChange}
              onReload={handleReload}
              streamInfo={storeState.streamInfo}
              mistStreamInfo={storeState.streamState?.streamInfo}
              currentPlayer={storeState.currentPlayerInfo}
              currentSource={storeState.currentSourceInfo}
              videoElement={storeState.videoElement}
              protocol={primaryEndpoint?.protocol}
              nodeId={primaryEndpoint?.nodeId}
              isVisible={storeState.isHovering || storeState.isPaused}
              isOpen={false}
              onOpenChange={(open) => (isDevPanelOpen = open)}
            />
          {/if}

          <!-- Speed indicator overlay -->
          {#if storeState.isHoldingSpeed}
            <SpeedIndicator isVisible={true} speed={storeState.holdSpeed} />
          {/if}

          <!-- Skip indicator overlay -->
          <SkipIndicator direction={skipDirection} seconds={10} onhide={handleSkipIndicatorHide} />

          <!-- Waiting for endpoint overlay -->
          {#if showWaitingForEndpoint && !showLoadingPosterOverlay}
            <IdleScreen status="OFFLINE" message={waitingMessage} />
          {/if}

          {#if showLoadingPosterOverlay}
            <div class="absolute inset-0 z-[4]">
              <LoadingPoster loadingPoster={storeState.loadingPoster} />
            </div>
          {/if}

          <!-- Idle screen -->
          {#if !showWaitingForEndpoint && storeState.shouldShowIdleScreen && !showLoadingPosterOverlay}
            <IdleScreen
              status={storeState.isEffectivelyLive ? storeState.streamState?.status : undefined}
              message={idleMessage}
              percentage={storeState.isEffectivelyLive
                ? storeState.streamState?.percentage
                : undefined}
              details={idleDetails}
            />
          {/if}

          <!-- Buffering spinner -->
          {#if showBufferingSpinner}
            <div role="status" aria-live="polite" class="fw-buffering-overlay">
              <div class="fw-buffering-pill">
                <div class="fw-buffering-spinner"></div>
                <span>{$translatorStore("buffering")}</span>
              </div>
            </div>
          {/if}

          <!-- Passive error toast (non-blocking) -->
          {#if displayedError && !storeState.shouldShowIdleScreen && displayedIsPassive}
            <div
              class={cn(
                "absolute bottom-20 left-1/2 -translate-x-1/2 z-30 transition-opacity duration-300",
                isErrorDismissing
                  ? "opacity-0"
                  : "animate-in fade-in slide-in-from-bottom-2 duration-200"
              )}
              role="status"
              aria-live="polite"
            >
              <div
                class="flex items-center gap-2 rounded-lg border border-yellow-500/30 bg-black/80 px-4 py-2 text-sm text-white shadow-lg backdrop-blur-sm"
              >
                <span class="text-yellow-400 text-xs font-semibold uppercase"
                  >{$translatorStore("warning")}</span
                >
                <span>{displayedError}</span>
                <button
                  type="button"
                  onclick={() => playerStore?.clearError()}
                  class="ml-2 text-white/60 hover:text-white"
                  aria-label={$translatorStore("dismiss")}
                >
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <path
                      d="M9 3L3 9M3 3L9 9"
                      stroke="currentColor"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                  </svg>
                </button>
              </div>
            </div>
          {/if}

          <!-- Fatal error overlay (blocking) — auto-dismisses on playback resume -->
          {#if displayedError && !storeState.shouldShowIdleScreen && !displayedIsPassive}
            <div
              role="alert"
              aria-live="assertive"
              class={cn(
                "fw-error-overlay fw-error-overlay--fullscreen transition-opacity duration-300",
                isErrorDismissing && "opacity-0"
              )}
            >
              <div class="fw-error-popup fw-error-popup--fullscreen">
                <div class="fw-error-header fw-error-header--error">
                  <span class="fw-error-title fw-error-title--error"
                    >{$translatorStore("error")}</span
                  >
                  <button
                    type="button"
                    class="fw-error-close"
                    onclick={() => playerStore?.clearError()}
                    aria-label={$translatorStore("dismiss")}
                  >
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                      <path
                        d="M9 3L3 9M3 3L9 9"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                      />
                    </svg>
                  </button>
                </div>
                <div class="fw-error-body">
                  <p class="fw-error-message">{displayedError}</p>
                </div>
                <div class="fw-error-actions">
                  <button
                    type="button"
                    class="fw-error-btn"
                    onclick={() => {
                      playerStore?.clearError();
                      playerStore?.retry();
                    }}
                    aria-label={$translatorStore("retry")}
                  >
                    {$translatorStore("retry")}
                  </button>
                  {#if options?.devMode && playerStore?.getController()?.canAttemptFallback()}
                    <button
                      type="button"
                      class="fw-error-btn fw-error-btn--secondary"
                      onclick={() => {
                        playerStore?.clearError();
                        playerStore?.getController()?.retryWithFallback();
                      }}
                      aria-label={$translatorStore("tryNext")}
                    >
                      {$translatorStore("tryNext")}
                    </button>
                  {/if}
                  {#if options?.devMode}
                    <button
                      type="button"
                      class="fw-error-btn fw-error-btn--secondary"
                      onclick={() => {
                        playerStore?.clearError();
                        playerStore?.reload();
                      }}
                      aria-label={$translatorStore("reloadPlayer")}
                    >
                      {$translatorStore("reloadPlayer")}
                    </button>
                  {/if}
                </div>
              </div>
            </div>
          {/if}

          <!-- Toast notification -->
          {#if storeState.toast}
            <div
              class="absolute bottom-20 left-1/2 -translate-x-1/2 z-30 animate-in fade-in slide-in-from-bottom-2 duration-200"
              role="status"
              aria-live="polite"
            >
              <div
                class="flex items-center gap-2 rounded-lg border border-white/10 bg-black/80 px-4 py-2 text-sm text-white shadow-lg backdrop-blur-sm"
              >
                <span>{storeState.toast.message}</span>
                <button
                  type="button"
                  onclick={() => playerStore?.dismissToast()}
                  class="ml-2 text-white/60 hover:text-white"
                  aria-label={$translatorStore("dismiss")}
                >
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <path
                      d="M9 3L3 9M3 3L9 9"
                      stroke="currentColor"
                      stroke-width="1.5"
                      stroke-linecap="round"
                    />
                  </svg>
                </button>
              </div>
            </div>
          {/if}

          <!-- Player controls — custom children or default -->
          {#if children}
            {@render children()}
          {:else if !useStockControls}
            <PlayerControls
              currentTime={storeState.currentTime}
              duration={storeState.duration}
              isVisible={storeState.shouldShowControls}
              onseek={(t) => playerStore?.seek(t)}
              disabled={!storeState.videoElement}
              sourceType={storeState.currentSourceInfo?.type}
              playbackMode={devPlaybackMode}
              onModeChange={handleModeChange}
              mistStreamInfo={storeState.streamState?.streamInfo}
              showStatsButton={false}
              {isStatsOpen}
              onStatsToggle={() => (isStatsOpen = !isStatsOpen)}
              isContentLive={storeState.isEffectivelyLive}
              onJumpToLive={() => playerStore?.getController()?.jumpToLive()}
              controllerSeekableStart={storeState?.controllerSeekableStart ?? 0}
              controllerLiveEdge={storeState?.controllerLiveEdge ?? 0}
              thumbnailCues={storeState?.thumbnailCues ?? []}
              {activeLocale}
              onLocaleChange={(l) => {
                activeLocale = l;
              }}
            />
          {/if}
        </div>

        <!-- Dev mode panel (when open) -->
        {#if options?.devMode && isDevPanelOpen}
          <DevModePanel
            onSettingsChange={handleDevSettingsChange}
            playbackMode={devPlaybackMode}
            onModeChange={handleModeChange}
            onReload={handleReload}
            streamInfo={storeState.streamInfo}
            mistStreamInfo={storeState.streamState?.streamInfo}
            currentPlayer={storeState.currentPlayerInfo}
            currentSource={storeState.currentSourceInfo}
            videoElement={storeState.videoElement}
            protocol={primaryEndpoint?.protocol}
            nodeId={primaryEndpoint?.nodeId}
            isVisible={true}
            isOpen={true}
            onOpenChange={(open) => (isDevPanelOpen = open)}
          />
        {/if}
      </div>
    {/snippet}
  </ContextMenuTrigger>

  <ContextMenuPortal>
    <ContextMenuContent>
      <ContextMenuItem
        onSelect={() => {
          isStatsOpen = !isStatsOpen;
        }}
      >
        <StatsIcon size={14} class="opacity-70 flex-shrink-0 mr-2" />
        {isStatsOpen ? $translatorStore("hideStats") : $translatorStore("showStats")}
      </ContextMenuItem>
      {#if options?.devMode}
        <ContextMenuSeparator />
        <ContextMenuItem
          onSelect={() => {
            isDevPanelOpen = !isDevPanelOpen;
          }}
        >
          <SettingsIcon size={14} class="opacity-70 flex-shrink-0 mr-2" />
          {isDevPanelOpen ? $translatorStore("hideSettings") : $translatorStore("settings")}
        </ContextMenuItem>
      {/if}
      <ContextMenuSeparator />
      <ContextMenuItem onSelect={() => playerStore?.togglePiP()}>
        <PictureInPictureIcon size={14} class="opacity-70 flex-shrink-0 mr-2" />
        {$translatorStore("pictureInPicture")}
      </ContextMenuItem>
      <ContextMenuItem onSelect={() => playerStore?.toggleLoop()}>
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="opacity-70 flex-shrink-0 mr-2"
        >
          <polyline points="17 1 21 5 17 9"></polyline>
          <path d="M3 11V9a4 4 0 0 1 4-4h14"></path>
          <polyline points="7 23 3 19 7 15"></polyline>
          <path d="M21 13v2a4 4 0 0 1-4 4H3"></path>
        </svg>
        {storeState.isLoopEnabled
          ? $translatorStore("disableLoop")
          : $translatorStore("enableLoop")}
      </ContextMenuItem>
    </ContextMenuContent>
  </ContextMenuPortal>
</ContextMenu>

// npm_player/packages/react/src/components/Player.tsx
import React, { useState, useCallback, useEffect, useMemo } from "react";
import IdleScreen from "./IdleScreen";
import LoadingPoster from "./LoadingPoster";
import TitleOverlay from "./TitleOverlay";
import StatsPanel from "./StatsPanel";
import PlayerControls from "./PlayerControls";
import DevModePanel from "./DevModePanel";
import SpeedIndicator from "./SpeedIndicator";
import type { SkipDirection } from "./SkipIndicator";
import SkipIndicator from "./SkipIndicator";
import { StatsIcon, SettingsIcon, PictureInPictureIcon } from "./Icons";
import type { PlayerProps } from "../types";
import { usePlayerController } from "../hooks/usePlayerController";
import { PlayerProvider } from "../context/PlayerContext";
import { I18nProvider } from "../context/I18nContext";
import {
  cn,
  themeOverridesToStyle,
  resolveTheme,
  createTranslator,
} from "@livepeer-frameworks/player-core";
import type {
  PlaybackMode,
  EndpointInfo,
  FwThemePreset,
  FwLocale,
} from "@livepeer-frameworks/player-core";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from "../ui/context-menu";

/**
 * Inner player component that uses PlayerController via hook
 */
const PlayerInner: React.FC<PlayerProps> = ({
  contentId,
  contentType,
  thumbnailUrl = null,
  options,
  endpoints: propsEndpoints,
  onStateChange,
  children,
}) => {
  // ============================================================================
  // UI-only State (stays in wrapper)
  // ============================================================================
  const [isStatsOpen, setIsStatsOpen] = useState(false);
  const [isDevPanelOpen, setIsDevPanelOpen] = useState(false);
  const [skipDirection, setSkipDirection] = useState<SkipDirection>(null);
  const [activeTheme, setActiveTheme] = useState<FwThemePreset>(options?.theme ?? "default");
  const [activeLocale, setActiveLocale] = useState<FwLocale>(options?.locale ?? "en");
  const t = useMemo(
    () => createTranslator({ locale: activeLocale, translations: options?.translations }),
    [activeLocale, options?.translations]
  );

  // Error fade-out: keep showing the overlay briefly while it animates out
  const [displayedError, setDisplayedError] = useState<string | null>(null);
  const [displayedIsPassive, setDisplayedIsPassive] = useState(false);
  const [isErrorDismissing, setIsErrorDismissing] = useState(false);

  // Sync theme/locale from props when parent changes them
  useEffect(() => {
    if (options?.theme) setActiveTheme(options.theme);
  }, [options?.theme]);
  useEffect(() => {
    if (options?.locale) setActiveLocale(options.locale);
  }, [options?.locale]);

  // Playback mode preference (persistent)
  const [devPlaybackMode, setDevPlaybackMode] = useState<PlaybackMode>(
    options?.playbackMode || "auto"
  );

  // ============================================================================
  // PlayerController Hook - ALL business logic
  // ============================================================================
  const playerHook = usePlayerController({
    contentId,
    contentType,
    endpoints: propsEndpoints,
    gatewayUrl: options?.gatewayUrl,
    mistUrl: options?.mistUrl,
    authToken: options?.authToken,
    playbackAuth: options?.playbackAuth,
    locale: options?.locale,
    translations: options?.translations,
    autoplay: options?.autoplay !== false,
    muted: options?.muted !== false,
    controls: options?.stockControls === true,
    poster: thumbnailUrl || undefined,
    debug: options?.debug,
    onStateChange: (playerState) => {
      onStateChange?.(playerState);
    },
    onError: (error) => {
      console.warn("[Player] Error:", error);
    },
  });

  const {
    containerRef,
    state,
    controller,
    togglePlay,
    toggleMute,
    toggleLoop,
    toggleFullscreen,
    togglePiP,
    setVolume,
    selectQuality,
    clearError,
    dismissToast,
    retry,
    reload,
    jumpToLive,
    handleMouseEnter,
    handleMouseLeave,
    handleMouseMove,
    setDevModeOptions,
  } = playerHook;

  // Error fade-out transition: when error clears, animate out before removing
  useEffect(() => {
    if (state.error) {
      setDisplayedError(state.error);
      setDisplayedIsPassive(state.isPassiveError);
      setIsErrorDismissing(false);
    } else if (displayedError) {
      setIsErrorDismissing(true);
      const timer = setTimeout(() => {
        setDisplayedError(null);
        setDisplayedIsPassive(false);
        setIsErrorDismissing(false);
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [state.error, state.isPassiveError]);

  // ============================================================================
  // Dev Mode Callbacks
  // ============================================================================
  const handleDevSettingsChange = useCallback(
    (settings: { forcePlayer?: string; forceType?: string; forceSource?: number }) => {
      // One-shot selection - controller handles the state
      setDevModeOptions({
        forcePlayer: settings.forcePlayer,
        forceType: settings.forceType,
        forceSource: settings.forceSource,
      });
    },
    [setDevModeOptions]
  );

  const handleModeChange = useCallback(
    (mode: PlaybackMode) => {
      setDevPlaybackMode(mode);
      // Mode is a persistent preference
      setDevModeOptions({ playbackMode: mode });
    },
    [setDevModeOptions]
  );

  const handleReload = useCallback(() => {
    clearError();
    reload();
  }, [clearError, reload]);

  const handleStatsToggle = useCallback(() => {
    setIsStatsOpen((prev) => !prev);
  }, []);

  // Clear skip indicator after animation
  const handleSkipIndicatorHide = useCallback(() => {
    setSkipDirection(null);
  }, []);

  // Auto-dismiss toast after 3 seconds
  useEffect(() => {
    if (!state.toast) return;
    const timer = setTimeout(() => {
      dismissToast();
    }, 3000);
    return () => clearTimeout(timer);
  }, [state.toast, dismissToast]);

  // ============================================================================
  // Derived Values
  // ============================================================================
  const primaryEndpoint = state.endpoints?.primary as EndpointInfo | undefined;
  const isLegacyPlayer = state.currentPlayerInfo?.shortname === "mist-legacy";
  const useStockControls = options?.stockControls === true || isLegacyPlayer;

  // Title overlay visibility: show on hover or when paused
  const showTitleOverlay =
    (state.isHovering || state.isPaused) &&
    !state.shouldShowIdleScreen &&
    !state.isBuffering &&
    !state.error;

  // Buffering spinner: only during active playback
  const showBufferingSpinner =
    !state.shouldShowIdleScreen && state.isBuffering && !state.error && state.hasPlaybackStarted;

  // ============================================================================
  // Waiting for Endpoint (shown as overlay, not early return)
  // ============================================================================
  const showWaitingForEndpoint = !state.endpoints?.primary && state.state !== "booting";
  const waitingMessage =
    state.state === "gateway_loading" ? t("resolvingEndpoint") : t("waitingForStream");
  const streamStateMessage = state.streamState?.message;
  const streamStateError = state.streamState?.error;
  const idleMessage = state.isEffectivelyLive
    ? streamStateError || streamStateMessage
    : t("loading");
  const idleDetails =
    options?.devMode &&
    streamStateError &&
    streamStateMessage &&
    streamStateError !== streamStateMessage
      ? streamStateMessage
      : undefined;
  // Controller owns the visibility decision (PlayerController.getShouldShowLoadingPoster).
  // Wrapper masks with its local displayedError fade lifecycle.
  const showLoadingPosterOverlay = state.shouldShowLoadingPoster && !displayedError;

  // ============================================================================
  // Render
  // ============================================================================
  return (
    <I18nProvider locale={activeLocale} translations={options?.translations}>
      <PlayerProvider value={playerHook}>
        <ContextMenu>
          <ContextMenuTrigger asChild>
            <div
              className={cn(
                "fw-player-surface fw-player-root w-full h-full overflow-hidden",
                options?.devMode && "flex"
              )}
              role="region"
              aria-label="Video player"
              data-player-container="true"
              data-theme={activeTheme && activeTheme !== "default" ? activeTheme : undefined}
              style={(() => {
                const presetOverrides = activeTheme ? resolveTheme(activeTheme) : null;
                const merged = { ...presetOverrides, ...options?.themeOverrides };
                return Object.keys(merged).length > 0 ? themeOverridesToStyle(merged) : undefined;
              })()}
              tabIndex={0}
              onMouseEnter={handleMouseEnter}
              onMouseLeave={handleMouseLeave}
              onMouseMove={handleMouseMove}
            >
              {/* Player area */}
              <div
                className={cn("relative", options?.devMode ? "flex-1 min-w-0" : "w-full h-full")}
              >
                {/* Video container - PlayerController attaches here */}
                <div ref={containerRef} className="fw-player-container" />

                {showLoadingPosterOverlay && (
                  <LoadingPoster
                    loadingPoster={state.loadingPoster}
                    className="absolute inset-0 z-[4]"
                  />
                )}

                {/* Title/Description overlay */}
                <TitleOverlay
                  title={state.metadata?.title}
                  description={state.metadata?.description}
                  isVisible={showTitleOverlay}
                />

                {/* Stats panel */}
                <StatsPanel
                  isOpen={isStatsOpen}
                  onClose={handleStatsToggle}
                  metadata={state.metadata}
                  streamState={state.streamState}
                  quality={state.playbackQuality}
                  videoElement={state.videoElement}
                  protocol={primaryEndpoint?.protocol}
                  nodeId={primaryEndpoint?.nodeId}
                  geoDistance={primaryEndpoint?.geoDistance}
                />

                {/* Dev Mode Panel toggle */}
                {options?.devMode && !isDevPanelOpen && (
                  <DevModePanel
                    onSettingsChange={handleDevSettingsChange}
                    playbackMode={devPlaybackMode}
                    onModeChange={handleModeChange}
                    onReload={handleReload}
                    streamInfo={state.streamInfo}
                    mistStreamInfo={state.streamState?.streamInfo}
                    currentPlayer={state.currentPlayerInfo}
                    currentSource={state.currentSourceInfo}
                    videoElement={state.videoElement}
                    protocol={primaryEndpoint?.protocol}
                    nodeId={primaryEndpoint?.nodeId}
                    isVisible={false}
                    isOpen={false}
                    onOpenChange={setIsDevPanelOpen}
                  />
                )}

                {/* Speed indicator */}
                {state.isHoldingSpeed && (
                  <SpeedIndicator isVisible={true} speed={state.holdSpeed} />
                )}

                {/* Skip indicator */}
                <SkipIndicator
                  direction={skipDirection}
                  seconds={10}
                  onHide={handleSkipIndicatorHide}
                />

                {/* Waiting for endpoint overlay */}
                {showWaitingForEndpoint && !showLoadingPosterOverlay && (
                  <IdleScreen status="OFFLINE" message={waitingMessage} />
                )}

                {/* Idle screen */}
                {!showWaitingForEndpoint &&
                  state.shouldShowIdleScreen &&
                  !showLoadingPosterOverlay && (
                    <IdleScreen
                      status={state.isEffectivelyLive ? state.streamState?.status : undefined}
                      message={idleMessage}
                      percentage={
                        state.isEffectivelyLive ? state.streamState?.percentage : undefined
                      }
                      details={idleDetails}
                    />
                  )}

                {/* Buffering spinner */}
                {showBufferingSpinner && (
                  <div role="status" aria-live="polite" className="fw-buffering-overlay">
                    <div className="fw-buffering-pill">
                      <div className="fw-buffering-spinner" />
                      <span>{t("buffering")}</span>
                    </div>
                  </div>
                )}

                {/* Passive error toast (non-blocking) */}
                {!state.shouldShowIdleScreen && displayedError && displayedIsPassive && (
                  <div
                    className={cn(
                      "absolute bottom-20 left-1/2 -translate-x-1/2 z-30 transition-opacity duration-300",
                      isErrorDismissing
                        ? "opacity-0"
                        : "animate-in fade-in slide-in-from-bottom-2 duration-200"
                    )}
                    role="status"
                    aria-live="polite"
                  >
                    <div className="flex items-center gap-2 rounded-lg border border-yellow-500/30 bg-black/80 px-4 py-2 text-sm text-white shadow-lg backdrop-blur-sm">
                      <span className="text-yellow-400 text-xs font-semibold uppercase">
                        {t("warning")}
                      </span>
                      <span>{displayedError}</span>
                      <button
                        type="button"
                        onClick={clearError}
                        className="ml-2 text-white/60 hover:text-white"
                        aria-label={t("dismiss")}
                      >
                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                          <path
                            d="M9 3L3 9M3 3L9 9"
                            stroke="currentColor"
                            strokeWidth="1.5"
                            strokeLinecap="round"
                          />
                        </svg>
                      </button>
                    </div>
                  </div>
                )}

                {/* Fatal error overlay (blocking) — auto-dismisses on playback resume */}
                {!state.shouldShowIdleScreen && displayedError && !displayedIsPassive && (
                  <div
                    role="alert"
                    aria-live="assertive"
                    className={cn(
                      "fw-error-overlay fw-error-overlay--fullscreen transition-opacity duration-300",
                      isErrorDismissing && "opacity-0"
                    )}
                  >
                    <div className="fw-error-popup fw-error-popup--fullscreen">
                      <div className="fw-error-header fw-error-header--error">
                        <span className="fw-error-title fw-error-title--error">{t("error")}</span>
                        <button
                          type="button"
                          className="fw-error-close"
                          onClick={clearError}
                          aria-label={t("dismiss")}
                        >
                          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                            <path
                              d="M9 3L3 9M3 3L9 9"
                              stroke="currentColor"
                              strokeWidth="1.5"
                              strokeLinecap="round"
                            />
                          </svg>
                        </button>
                      </div>
                      <div className="fw-error-body">
                        <p className="fw-error-message">{displayedError}</p>
                      </div>
                      <div className="fw-error-actions">
                        <button
                          type="button"
                          className="fw-error-btn"
                          aria-label={t("retry")}
                          onClick={() => {
                            clearError();
                            retry();
                          }}
                        >
                          {t("retry")}
                        </button>
                        {options?.devMode && controller?.canAttemptFallback?.() && (
                          <button
                            type="button"
                            className="fw-error-btn fw-error-btn--secondary"
                            aria-label={t("tryNext")}
                            onClick={() => {
                              clearError();
                              controller?.retryWithFallback();
                            }}
                          >
                            {t("tryNext")}
                          </button>
                        )}
                        {options?.devMode && (
                          <button
                            type="button"
                            className="fw-error-btn fw-error-btn--secondary"
                            aria-label={t("reloadPlayer")}
                            onClick={() => {
                              clearError();
                              reload();
                            }}
                          >
                            {t("reloadPlayer")}
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                {/* Toast notification */}
                {state.toast && (
                  <div
                    className="absolute bottom-20 left-1/2 -translate-x-1/2 z-30 animate-in fade-in slide-in-from-bottom-2 duration-200"
                    role="status"
                    aria-live="polite"
                  >
                    <div className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/80 px-4 py-2 text-sm text-white shadow-lg backdrop-blur-sm">
                      <span>{state.toast.message}</span>
                      <button
                        type="button"
                        onClick={dismissToast}
                        className="ml-2 text-white/60 hover:text-white"
                        aria-label={t("dismiss")}
                      >
                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                          <path
                            d="M9 3L3 9M3 3L9 9"
                            stroke="currentColor"
                            strokeWidth="1.5"
                            strokeLinecap="round"
                          />
                        </svg>
                      </button>
                    </div>
                  </div>
                )}

                {/* Player controls — custom children or default */}
                {children
                  ? children
                  : !useStockControls && (
                      <PlayerControls
                        currentTime={state.currentTime}
                        duration={state.duration}
                        isVisible={state.shouldShowControls}
                        onSeek={(t) => controller?.seek(t)}
                        showStatsButton={false}
                        isStatsOpen={isStatsOpen}
                        onStatsToggle={handleStatsToggle}
                        mistStreamInfo={state.streamState?.streamInfo}
                        disabled={!state.videoElement}
                        playbackMode={devPlaybackMode}
                        onModeChange={handleModeChange}
                        sourceType={state.currentSourceInfo?.type}
                        isContentLive={state.isEffectivelyLive}
                        // Props from usePlayerController hook
                        videoElement={state.videoElement}
                        qualities={state.qualities}
                        onSelectQuality={selectQuality}
                        isMuted={state.isMuted}
                        volume={state.volume}
                        onVolumeChange={setVolume}
                        onToggleMute={toggleMute}
                        isPlaying={state.isPlaying}
                        onTogglePlay={togglePlay}
                        onToggleFullscreen={toggleFullscreen}
                        isFullscreen={state.isFullscreen}
                        isLoopEnabled={state.isLoopEnabled}
                        onToggleLoop={toggleLoop}
                        onJumpToLive={jumpToLive}
                        activeLocale={activeLocale}
                        translations={options?.translations}
                        onLocaleChange={setActiveLocale}
                        thumbnailCues={state.thumbnailCues}
                      />
                    )}
              </div>

              {/* Dev Mode Panel - side panel */}
              {options?.devMode && isDevPanelOpen && (
                <DevModePanel
                  onSettingsChange={handleDevSettingsChange}
                  playbackMode={devPlaybackMode}
                  onModeChange={handleModeChange}
                  onReload={handleReload}
                  streamInfo={state.streamInfo}
                  mistStreamInfo={state.streamState?.streamInfo}
                  currentPlayer={state.currentPlayerInfo}
                  currentSource={state.currentSourceInfo}
                  videoElement={state.videoElement}
                  protocol={primaryEndpoint?.protocol}
                  nodeId={primaryEndpoint?.nodeId}
                  isVisible={true}
                  isOpen={true}
                  onOpenChange={setIsDevPanelOpen}
                />
              )}
            </div>
          </ContextMenuTrigger>

          {/* Context menu */}
          <ContextMenuContent>
            <ContextMenuItem onSelect={handleStatsToggle} className="gap-2">
              <StatsIcon size={14} className="opacity-70 flex-shrink-0" />
              <span>{isStatsOpen ? t("hideStats") : t("showStats")}</span>
            </ContextMenuItem>
            {options?.devMode && (
              <>
                <ContextMenuSeparator />
                <ContextMenuItem
                  onSelect={() => setIsDevPanelOpen(!isDevPanelOpen)}
                  className="gap-2"
                >
                  <SettingsIcon size={14} className="opacity-70 flex-shrink-0" />
                  <span>{isDevPanelOpen ? t("hideSettings") : t("settings")}</span>
                </ContextMenuItem>
              </>
            )}
            <ContextMenuSeparator />
            <ContextMenuItem onSelect={togglePiP} className="gap-2">
              <PictureInPictureIcon size={14} className="opacity-70 flex-shrink-0" />
              <span>{t("pictureInPicture")}</span>
            </ContextMenuItem>
            <ContextMenuItem onSelect={toggleLoop} className="gap-2">
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="opacity-70 flex-shrink-0"
              >
                <polyline points="17 1 21 5 17 9"></polyline>
                <path d="M3 11V9a4 4 0 0 1 4-4h14"></path>
                <polyline points="7 23 3 19 7 15"></polyline>
                <path d="M21 13v2a4 4 0 0 1-4 4H3"></path>
              </svg>
              <span>{state.isLoopEnabled ? t("disableLoop") : t("enableLoop")}</span>
            </ContextMenuItem>
          </ContextMenuContent>
        </ContextMenu>
      </PlayerProvider>
    </I18nProvider>
  );
};

/**
 * Main Player component.
 *
 * Note: PlayerProvider is available if you need to use context-based access
 * across multiple components. PlayerInner manages its own PlayerController
 * via usePlayerController hook.
 */
const Player: React.FC<PlayerProps> = (props) => {
  return <PlayerInner {...props} />;
};

export default Player;
